services:

    leos.use_case.security_command:
        class: Leos\Application\UseCase\Security\LoginHandler
        tags:
          - { name: tactician.handler, command: Leos\Application\UseCase\Security\Request\Login }
        arguments:
          - "@security.authentication_utils"
          - "@leos.repository.user"
          - "@security.encoder_factory"
          - "@lexik_jwt_authentication.jwt_manager"
