imports:
    - { resource: services/common.yml }

services:

    leos.controller.monitor:
      class: Leos\UI\RestBundle\Controller\Monitor\StatusController
      parent: leos.abstract.controller

    leos.controller.wallet:
      class: Leos\UI\RestBundle\Controller\Wallet\WalletController
      parent: leos.abstract.controller
      arguments:
        - "@leos.use_case.wallet"
