imports:
    - { resource: services/common.yml }

services:

    leos.controller.home:
      class: Leos\UI\RestBundle\Controller\Home\HomeController
      parent: leos.abstract.controller
      arguments:
        - "@fos_rest.router"

    leos.controller.security:
      class: Leos\UI\RestBundle\Controller\Security\SecurityController
      parent: leos.abstract.controller
      arguments:
        - "@leos.use_case.security_command"

    leos.controller.monitor:
      class: Leos\UI\RestBundle\Controller\Monitor\StatusController
      parent: leos.abstract.controller

    leos.controller.wallet:
      class: Leos\UI\RestBundle\Controller\Wallet\WalletController
      parent: leos.abstract.controller
      arguments:
        - "@leos.use_case.wallet_query"
        - "@leos.use_case.transaction_command"
