stages:
  - build
  - release

before_script:
  - export RELEASE=${CI_BUILD_REF_NAME}
  - echo $PWD

build:
  stage: build
  script:
    - connect
    - cd etc/infrastructure
    - mkdir -p context-${RELEASE}/build
    - docker-compose -f build/docker-compose.yml build
    - docker-compose -f build/docker-compose.yml up -d
    - sleep 8
    - docker exec sf-build-${RELEASE} php bin/console d:s:u --force

    - docker exec sf-build-${RELEASE} phpunit --colors=never
    - docker exec sf-build-${RELEASE} ./vendor/bin/behat
    - docker-compose -f build/docker-compose.yml down --rmi local --volumes

    - mkdir -p context-${RELEASE}/build
    - docker build -t sf-build-${RELEASE} -f build/fpm/Dockerfile ../../

release:tags:
  stage: release
  only:
    - tags

  script:
    - connect
    - docker run -d --name building-${RELEASE} sf-build-${RELEASE}
    - docker cp building-${RELEASE}:/app context-${RELEASE}/build/
    - docker rm -f building-${RELEASE}
    - cp -R prod/fpm context-${RELEASE}/build/fpm
    - cp -R prod/nginx context-${RELEASE}/build/nginx
    - docker-compose -f prod/docker-compose.build.yml build
    - docker-compose -f prod/docker-compose.build.yml push
