services:

    leos.use_case.wallet_query:
        class: Leos\Application\UseCase\Wallet\WalletQuery
        autowire: true

    leos.use_case.transaction_command:
        class: Leos\Application\UseCase\Transaction\TransactionCommand
        autowire: true

    leos.use_case.security_command:
        class: Leos\Application\UseCase\Security\SecurityCommand
        arguments:
          - "@security.authentication_utils"
          - "@leos.repository.user"
          - "@security.encoder_factory"
          - "@lexik_jwt_authentication.jwt_manager"

    leos.use_case.user_command:
        class: Leos\Application\UseCase\User\UserCommand
        arguments:
          - "@leos.repository.user"
          - "@leos.factory.user"

    leos.use_case.user_query:
        class: Leos\Application\UseCase\User\UserQuery
        arguments:
          - "@leos.repository.user"
