services:

    leos.use_case.wallet_query:
        class: Leos\Application\UseCase\Wallet\WalletQuery
        autowire: true

    leos.use_case.transaction_command:
        class: Leos\Application\UseCase\Transaction\TransactionCommand
        autowire: true


