# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        harsh:
            algorithm: bcrypt
            cost: 15

    providers:
        customers:
            entity: { class: Leos\Infrastructure\SecurityBundle\Security\Model\Auth, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            stateless:  true

        login_firewall:
            pattern:   ^/login$
            anonymous: ~

        secured_area:
            provider: customers
            pattern:    ^/api/*/user
            form_login:
                login_path: login
                check_path: login

        main:
            anonymous: ~
            stateless:  true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
