# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    leos.abstract.repository:
        abstract: true
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        public: false

    leos.abstract.form_factory:
        abstract: true
        arguments: ["@form.factory"]
