imports:
    - { resource: services/common.yml }

services:

    leos.controller.monitor:
      class: Leos\Application\RestBundle\Controller\Monitor\StatusController
      parent: leos.abstract.controller
