Leos\Domain\Transaction\Model\Transaction:
    type: entity
    table: transaction
    repositoryClass: Leos\Infrastructure\TransactionBundle\Repository\TransactionRepository
    id:
      id:
        type: string
        nullable: false
        id: true
        generator:
          strategy: UUID

    fields:
      type:
        type: string

      createdAt:
        type: datetime

      updatedAt:
        type: datetime
        nullable: true

      operationReal:
        type: integer

      operationBonus:
        type: integer

    embedded:
      prevReal:
        class: Leos\Domain\Wallet\ValueObject\Credit

      prevBonus:
        class: Leos\Domain\Wallet\ValueObject\Credit

    manyToOne:
        wallet:
          targetEntity: Leos\Domain\Wallet\Model\Wallet
          joinColumn:
            name: wallet_id
            referencedColumnName: id

        referralTransaction:
          targetEntity: Leos\Domain\Transaction\Model\Transaction
          joinColumn:
            name: transaction_id
            referencedColumnName: id
            nullble: true

    lifecycleCallbacks: {  }
