imports:
    - { resource: services/common.yml }

services:

    leos.controller.home:
      class: Leos\UI\RestBundle\Controller\Home\HomeController
      parent: leos.abstract.controller
      arguments:
        - "@fos_rest.router"

    leos.controller.security:
      class: Leos\UI\RestBundle\Controller\Security\SecurityController
      parent: leos.abstract.controller
      arguments:
        - "@leos.application.security_command"
        - "@leos.application.user_command"

    leos.controller.monitor:
      class: Leos\UI\RestBundle\Controller\Monitor\StatusController
      parent: leos.abstract.controller

    leos.controller.wallet:
      class: Leos\UI\RestBundle\Controller\Wallet\WalletController
      parent: leos.abstract.controller
      arguments:
        - "@leos.application.wallet_query"
        - "@leos.application.transaction_command"

    leos.controller.wallet_rollback:
      class: Leos\UI\RestBundle\Controller\Rollback\RollbackController
      parent: leos.abstract.controller
      arguments:
        - "@leos.application.transaction_command"

    leos.controller.user:
      class: Leos\UI\RestBundle\Controller\User\UserController
      parent: leos.abstract.controller
      arguments:
        - "@leos.application.user_command"
        - "@leos.application.user_query"
