Leos\Domain\Transaction\Model\Transaction:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [Identifier]

        type:
            expose: true
            groups: [Basic]

        operationReal:
            expose: true
            groups: [Basic]

        operationBonus:
            expose: true
            groups: [Basic]

        prevReal:
            expose: true
            groups: [Basic]
            type: Leos\Domain\Wallet\ValueObject\Credit

        prevBonus:
            expose: true
            groups: [Basic]
            type: Leos\Domain\Wallet\ValueObject\Credit

        createdAt:
            expose: true
            groups: [Basic]

        updatedAt:
            expose: true
            groups: [Basic]

        wallet:
            expose: true
            groups: [Basic]
            type: Leos\Domain\Wallet\Model\Wallet

        referralTransaction:
            expose: true
            groups: [Basic]
            type: Leos\Domain\Transaction\Model\Transaction
